//! Accessibility notification constants and priorities.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(isize)]
pub enum AXPriority {
    Low = 10,
    Medium = 50,
    High = 90,
}

impl AXPriority {
    #[must_use]
    pub const fn raw(self) -> isize {
        self as isize
    }
}

pub const AX_MAIN_WINDOW_CHANGED_NOTIFICATION: &str = "AXMainWindowChanged";
pub const AX_FOCUSED_WINDOW_CHANGED_NOTIFICATION: &str = "AXFocusedWindowChanged";
pub const AX_FOCUSED_UI_ELEMENT_CHANGED_NOTIFICATION: &str = "AXFocusedUIElementChanged";
pub const AX_APPLICATION_ACTIVATED_NOTIFICATION: &str = "AXApplicationActivated";
pub const AX_APPLICATION_DEACTIVATED_NOTIFICATION: &str = "AXApplicationDeactivated";
pub const AX_APPLICATION_HIDDEN_NOTIFICATION: &str = "AXApplicationHidden";
pub const AX_APPLICATION_SHOWN_NOTIFICATION: &str = "AXApplicationShown";
pub const AX_WINDOW_CREATED_NOTIFICATION: &str = "AXWindowCreated";
pub const AX_WINDOW_MOVED_NOTIFICATION: &str = "AXWindowMoved";
pub const AX_WINDOW_RESIZED_NOTIFICATION: &str = "AXWindowResized";
pub const AX_WINDOW_MINIATURIZED_NOTIFICATION: &str = "AXWindowMiniaturized";
pub const AX_WINDOW_DEMINIATURIZED_NOTIFICATION: &str = "AXWindowDeminiaturized";
pub const AX_DRAWER_CREATED_NOTIFICATION: &str = "AXDrawerCreated";
pub const AX_SHEET_CREATED_NOTIFICATION: &str = "AXSheetCreated";
pub const AX_HELP_TAG_CREATED_NOTIFICATION: &str = "AXHelpTagCreated";
pub const AX_VALUE_CHANGED_NOTIFICATION: &str = "AXValueChanged";
pub const AXUI_ELEMENT_DESTROYED_NOTIFICATION: &str = "AXUIElementDestroyed";
pub const AX_ELEMENT_BUSY_CHANGED_NOTIFICATION: &str = "AXElementBusyChanged";
pub const AX_MENU_OPENED_NOTIFICATION: &str = "AXMenuOpened";
pub const AX_MENU_CLOSED_NOTIFICATION: &str = "AXMenuClosed";
pub const AX_MENU_ITEM_SELECTED_NOTIFICATION: &str = "AXMenuItemSelected";
pub const AX_ROW_COUNT_CHANGED_NOTIFICATION: &str = "AXRowCountChanged";
pub const AX_ROW_EXPANDED_NOTIFICATION: &str = "AXRowExpanded";
pub const AX_ROW_COLLAPSED_NOTIFICATION: &str = "AXRowCollapsed";
pub const AX_SELECTED_CELLS_CHANGED_NOTIFICATION: &str = "AXSelectedCellsChanged";
pub const AX_UNITS_CHANGED_NOTIFICATION: &str = "AXUnitsChanged";
pub const AX_SELECTED_CHILDREN_MOVED_NOTIFICATION: &str = "AXSelectedChildrenMoved";
pub const AX_SELECTED_CHILDREN_CHANGED_NOTIFICATION: &str = "AXSelectedChildrenChanged";
pub const AX_RESIZED_NOTIFICATION: &str = "AXResized";
pub const AX_MOVED_NOTIFICATION: &str = "AXMoved";
pub const AX_CREATED_NOTIFICATION: &str = "AXCreated";
pub const AX_SELECTED_ROWS_CHANGED_NOTIFICATION: &str = "AXSelectedRowsChanged";
pub const AX_SELECTED_COLUMNS_CHANGED_NOTIFICATION: &str = "AXSelectedColumnsChanged";
pub const AX_SELECTED_TEXT_CHANGED_NOTIFICATION: &str = "AXSelectedTextChanged";
pub const AX_TITLE_CHANGED_NOTIFICATION: &str = "AXTitleChanged";
pub const AX_LAYOUT_CHANGED_NOTIFICATION: &str = "AXLayoutChanged";
pub const AX_ANNOUNCEMENT_REQUESTED_NOTIFICATION: &str = "AXAnnouncementRequested";

pub const ALL_NOTIFICATIONS: &[&str] = &[
    AX_MAIN_WINDOW_CHANGED_NOTIFICATION,
    AX_FOCUSED_WINDOW_CHANGED_NOTIFICATION,
    AX_FOCUSED_UI_ELEMENT_CHANGED_NOTIFICATION,
    AX_APPLICATION_ACTIVATED_NOTIFICATION,
    AX_APPLICATION_DEACTIVATED_NOTIFICATION,
    AX_APPLICATION_HIDDEN_NOTIFICATION,
    AX_APPLICATION_SHOWN_NOTIFICATION,
    AX_WINDOW_CREATED_NOTIFICATION,
    AX_WINDOW_MOVED_NOTIFICATION,
    AX_WINDOW_RESIZED_NOTIFICATION,
    AX_WINDOW_MINIATURIZED_NOTIFICATION,
    AX_WINDOW_DEMINIATURIZED_NOTIFICATION,
    AX_DRAWER_CREATED_NOTIFICATION,
    AX_SHEET_CREATED_NOTIFICATION,
    AX_HELP_TAG_CREATED_NOTIFICATION,
    AX_VALUE_CHANGED_NOTIFICATION,
    AXUI_ELEMENT_DESTROYED_NOTIFICATION,
    AX_ELEMENT_BUSY_CHANGED_NOTIFICATION,
    AX_MENU_OPENED_NOTIFICATION,
    AX_MENU_CLOSED_NOTIFICATION,
    AX_MENU_ITEM_SELECTED_NOTIFICATION,
    AX_ROW_COUNT_CHANGED_NOTIFICATION,
    AX_ROW_EXPANDED_NOTIFICATION,
    AX_ROW_COLLAPSED_NOTIFICATION,
    AX_SELECTED_CELLS_CHANGED_NOTIFICATION,
    AX_UNITS_CHANGED_NOTIFICATION,
    AX_SELECTED_CHILDREN_MOVED_NOTIFICATION,
    AX_SELECTED_CHILDREN_CHANGED_NOTIFICATION,
    AX_RESIZED_NOTIFICATION,
    AX_MOVED_NOTIFICATION,
    AX_CREATED_NOTIFICATION,
    AX_SELECTED_ROWS_CHANGED_NOTIFICATION,
    AX_SELECTED_COLUMNS_CHANGED_NOTIFICATION,
    AX_SELECTED_TEXT_CHANGED_NOTIFICATION,
    AX_TITLE_CHANGED_NOTIFICATION,
    AX_LAYOUT_CHANGED_NOTIFICATION,
    AX_ANNOUNCEMENT_REQUESTED_NOTIFICATION,
];

pub const AXUI_ELEMENTS_KEY: &str = "AXUIElementsKey";
pub const AX_PRIORITY_KEY: &str = "AXPriorityKey";
pub const AX_ANNOUNCEMENT_KEY: &str = "AXAnnouncementKey";
pub const AXUI_ELEMENT_TITLE_KEY: &str = "AXUIElementTitleKey";

pub const INFO_KEYS: &[&str] = &[
    AXUI_ELEMENTS_KEY,
    AX_PRIORITY_KEY,
    AX_ANNOUNCEMENT_KEY,
    AXUI_ELEMENT_TITLE_KEY,
];
